import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Spinninglogo from "@/components/Spinninglogo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Navbar/>
        

        <div className="flex mt-17 px-15 min-h-screen pt-40">
          {/* Main content */}
          <div className="flex w-[82%] items-center justify-center">
            {children}
          </div>

          {/* Spinning Logo appears on every page */}
          <div className="flex w-[18%] max-h-[12rem] items-end justify-end">
            <Spinninglogo />
          </div>
        </div>
      </body>
    </html>
  );
}
